---
- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt
  become: yes

- name: create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755
  become: yes
  become_user: centos

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/centos/.kube/config
    remote_src: yes
    owner: centos
  become: yes

- name: install Pod network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt
  become: yes
  become_user: centos


- name: Get join command for workers
  shell: kubeadm token create --print-join-command
  register: join_command_stdout

- name: Persist variable for workers
  set_fact:
    join_command: "{{ join_command_stdout.stdout_lines[0] }}"

