apiVersion: v1
kind: Service
metadata:
  name: anagram-app
  labels:
    run: anagram-app
spec:
  ports:
  - port: 5000
    nodePort: 31234
    targetPort: 5000
    protocol: TCP
  type: NodePort
  selector:
    run: anagram-app

